# Generated by Django 5.0 on 2023-12-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_order_address_order_city_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
