# Generated by Django 5.0 on 2023-12-28 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_order_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
