# Generated by Django 5.0 on 2023-12-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rename_phone_number_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone_num',
        ),
    ]
